#ifndef DEVICE_DATA_H_
#define DEVICE_DATA_H_

#define OPENER_DEVICE_VENDOR_ID      55512
#define OPENER_DEVICE_TYPE           7
#define OPENER_DEVICE_PRODUCT_CODE   1
#define OPENER_DEVICE_MAJOR_REVISION 1
#define OPENER_DEVICE_MINOR_REVISION 0
#define OPENER_DEVICE_NAME           "ENIP-Scale"
#define OPENER_DEVICE_SERIAL_NUMBER  123456789


#endif

