/*
 * Copyright (c) 2025, Adam G. Sweeney <agsweeney@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "webui_api.h"
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>

const char *webui_get_index_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>Device Configuration</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".alert-info { color: #0c5460; background-color: #d1ecf1; border-color: #bee5eb; }"
           ".status-card { border: 1px solid #ddd; border-radius: 8px; padding: 0; margin-bottom: 20px; background-color: #fff; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 15px 20px; border-bottom: 1px solid #dee2e6; margin: 0; }"
           ".card-header h2 { margin: 0; color: #212529; font-size: 1.25rem; font-weight: 600; }"
           ".card-body { padding: 20px; }"
           "input[type=\"checkbox\"] { width: 18px; height: 18px; margin-right: 8px; vertical-align: middle; }"
           ".page { display: block; }"
           ".page.hidden { display: none; }"
           ".nav-link.active { background-color: #007bff; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\" class=\"nav-link\">Device Configuration</a></li>"
           "<li><a href=\"/nau7802\" class=\"nav-link\">NAU7802 Scale</a></li>"
           "<li><a href=\"/ota\" class=\"nav-link\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div id=\"config-page\" class=\"page\">"
           "<div class=\"page-header\">"
           "<h1>Device Configuration</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div id=\"message\" class=\"alert\" style=\"display: none;\"></div>"
           
           "<!-- Network Configuration -->"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Network Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<form id=\"ipConfigForm\">"
           "<div class=\"form-group\">"
           "<label>"
           "<input type=\"checkbox\" id=\"use_dhcp\" onchange=\"toggleStaticFields()\">"
           "<span>Use DHCP (Automatic IP Assignment)</span>"
           "</label>"
           "</div>"
           "<div id=\"staticIpFields\" style=\"display: none;\">"
           "<div class=\"form-group\">"
           "<label for=\"ip_address\">IP Address:</label>"
           "<input type=\"text\" id=\"ip_address\" class=\"form-control\" placeholder=\"192.168.1.100\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"netmask\">Netmask:</label>"
           "<input type=\"text\" id=\"netmask\" class=\"form-control\" placeholder=\"255.255.255.0\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"gateway\">Gateway:</label>"
           "<input type=\"text\" id=\"gateway\" class=\"form-control\" placeholder=\"192.168.1.1\">"
           "</div>"
           "</div>"
           "<div id=\"dnsFields\" style=\"display: none;\">"
           "<div class=\"form-group\">"
           "<label for=\"dns1\">Primary DNS:</label>"
           "<input type=\"text\" id=\"dns1\" class=\"form-control\" placeholder=\"8.8.8.8\">"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"dns2\">Secondary DNS:</label>"
           "<input type=\"text\" id=\"dns2\" class=\"form-control\" placeholder=\"8.8.4.4\">"
           "</div>"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveIpConfig()\">Save Network Configuration</button>"
           "</form>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message') || document.getElementById('nau7802_message');"
           "  if (msg) {"
           "    msg.textContent = text;"
           "    msg.className = 'alert alert-' + type;"
           "    msg.style.display = 'block';"
           "    setTimeout(function() { msg.style.display = 'none'; }, 5000);"
           "  } else {"
           "    console.log('[' + type.toUpperCase() + '] ' + text);"
           "  }"
           "}"
           "function showPage(pageName) {"
           "  const pages = document.querySelectorAll('.page');"
           "  const navLinks = document.querySelectorAll('.nav-link');"
           "  pages.forEach(p => p.style.display = 'none');"
           "  navLinks.forEach(l => l.classList.remove('active'));"
           "  const targetPage = document.getElementById(pageName + '-page');"
           "  const targetLink = document.querySelector('[data-page=' + pageName + ']');"
           "  if (targetPage) targetPage.style.display = 'block';"
           "  if (targetLink) targetLink.classList.add('active');"
           "  if (pageName === 'nau7802') {"
           "    loadNau7802Config();"
           "    if (!window.nau7802StatusInterval) {"
           "      window.nau7802StatusInterval = setInterval(updateNau7802Status, 2000);"
           "    }"
           "  }"
           "}"
           "function loadIpConfig() {"
           "  fetch('/api/ipconfig')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const dhcpCheckbox = document.getElementById('use_dhcp');"
           "      const staticFields = document.getElementById('staticIpFields');"
           "      const dnsFields = document.getElementById('dnsFields');"
           "      if (dhcpCheckbox && data.use_dhcp !== undefined) {"
           "        dhcpCheckbox.checked = data.use_dhcp;"
           "        toggleStaticFields();"
           "      }"
           "      const ipAddr = document.getElementById('ip_address');"
           "      const netmask = document.getElementById('netmask');"
           "      const gateway = document.getElementById('gateway');"
           "      const dns1 = document.getElementById('dns1');"
           "      const dns2 = document.getElementById('dns2');"
           "      if (ipAddr) ipAddr.value = (data.ip_address && data.ip_address !== '0.0.0.0') ? data.ip_address : '';"
           "      if (netmask) netmask.value = (data.netmask && data.netmask !== '0.0.0.0') ? data.netmask : '';"
           "      if (gateway) gateway.value = (data.gateway && data.gateway !== '0.0.0.0') ? data.gateway : '';"
           "      if (dns1) dns1.value = (data.dns1 && data.dns1 !== '0.0.0.0') ? data.dns1 : '';"
           "      if (dns2) dns2.value = (data.dns2 && data.dns2 !== '0.0.0.0') ? data.dns2 : '';"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load IP configuration:', err);"
           "    });"
           "}"
           "function toggleStaticFields() {"
           "  const dhcpCheckbox = document.getElementById('use_dhcp');"
           "  const staticFields = document.getElementById('staticIpFields');"
           "  const dnsFields = document.getElementById('dnsFields');"
           "  if (dhcpCheckbox && staticFields && dnsFields) {"
           "    const useDhcp = dhcpCheckbox.checked;"
           "    staticFields.style.display = useDhcp ? 'none' : 'block';"
           "    dnsFields.style.display = useDhcp ? 'none' : 'block';"
           "  }"
           "}"
           "function saveIpConfig() {"
           "  const data = {"
           "    use_dhcp: document.getElementById('use_dhcp').checked,"
           "    ip_address: document.getElementById('ip_address').value,"
           "    netmask: document.getElementById('netmask').value,"
           "    gateway: document.getElementById('gateway').value,"
           "    dns1: document.getElementById('dns1').value,"
           "    dns2: document.getElementById('dns2').value"
           "  };"
           "  fetch('/api/ipconfig', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message, 'success');"
           "      } else {"
           "        showMessage('Failed to save IP configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save IP configuration:', err);"
           "      showMessage('Failed to save IP configuration', 'danger');"
           "    });"
           "}"
           "window.onload = function() {"
           "  loadIpConfig();"
           "};"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_status_html(void)
{
    return "";  // Status page removed
}

const char *webui_get_ethernetip_html(void)
{
    return "";  // Output assembly page removed
}

const char *webui_get_input_assembly_html(void)
{
    return "";  // Input assembly page removed
}

const char *webui_get_mcpconfig_html(void)
{
    return "";  // MCP230x removed from project
}

const char *webui_get_vl53l1xconfig_html(void)
{
    return "";  // VL53L1x removed from project
}

const char *webui_get_mpu6050_html(void)
{
    return "";  // Removed - use API instead
}

const char *webui_get_ota_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>Firmware Update</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           "input[type=\"file\"] { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; cursor: pointer; }"
           "input[type=\"file\"]::-webkit-file-upload-button { padding: 6px 12px; margin-right: 12px; color: #fff; background-color: #007bff; border: 1px solid #007bff; border-radius: 4px; cursor: pointer; font-size: 14px; font-weight: 400; }"
           "input[type=\"file\"]::-webkit-file-upload-button:hover { background-color: #0069d9; border-color: #0062cc; }"
           "input[type=\"file\"]::file-selector-button { padding: 6px 12px; margin-right: 12px; color: #fff; background-color: #007bff; border: 1px solid #007bff; border-radius: 4px; cursor: pointer; font-size: 14px; font-weight: 400; }"
           "input[type=\"file\"]::file-selector-button:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".alert-warning { color: #856404; background-color: #fff3cd; border-color: #ffeaa7; }"
           ".alert-info { color: #0c5460; background-color: #d1ecf1; border-color: #bee5eb; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Device Configuration</a></li>"
           "<li><a href=\"/nau7802\">NAU7802 Scale</a></li>"
           "<li><a href=\"/ota\" class=\"active\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>Firmware Update</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div style=\"margin-bottom: 20px; padding: 12px; background-color: #f8f9fa; border-left: 4px solid #007bff; border-radius: 4px;\">"
           "<p style=\"margin: 0; color: #495057; font-size: 14px; line-height: 1.6;\">"
           "<strong>Over-The-Air (OTA) Firmware Update:</strong> Upload a new firmware binary file (.bin) to update the device firmware wirelessly. "
           "Select the firmware file and click \"Start Update\" to begin the process. The device will automatically reboot after a successful update. "
           "Ensure the firmware file is compatible with your device model and that you maintain a stable network connection during the update process."
           "</p>"
           "</div>"
           "<div id=\"message\" class=\"alert\" style=\"display: none;\"></div>"
           "<form id=\"otaForm\">"
           "<div class=\"form-group\">"
           "<label for=\"firmware_file\">Firmware File (.bin):</label>"
           "<input type=\"file\" id=\"firmware_file\" class=\"form-control\" accept=\".bin\">"
           "</div>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"startOTA()\" style=\"margin-top:20px;\">Start Update</button>"
           "</form>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('message');"
           "  if (msg) {"
           "    msg.textContent = text;"
           "    msg.className = 'alert alert-' + type;"
           "    msg.style.display = 'block';"
           "  } else {"
           "    console.log('[' + type.toUpperCase() + '] ' + text);"
           "  }"
           "}"
           "function startOTA() {"
           "  const fileInput = document.getElementById('firmware_file');"
           "  if (!fileInput) {"
           "    showMessage('Error: File input not found', 'danger');"
           "    return;"
           "  }"
           "  const file = fileInput.files[0];"
           "  if (!file) {"
           "    showMessage('Please select a firmware file', 'warning');"
           "    return;"
           "  }"
           "  const formData = new FormData();"
           "  formData.append('firmware', file);"
           "  showMessage('Uploading firmware...', 'info');"
           "  fetch('/api/ota/update', {"
           "    method: 'POST',"
           "    body: formData"
           "  })"
           "    .then(function(r) {"
           "      if (!r.ok) {"
           "        throw new Error('HTTP ' + r.status);"
           "      }"
           "      return r.json();"
           "    })"
           "    .then(function(data) {"
           "      if (data.status === 'ok') {"
           "        showMessage('Firmware uploaded successfully. Device will reboot in a few seconds...', 'success');"
           "        setTimeout(function() {"
           "          window.location.href = '/';"
           "        }, 5000);"
           "      } else {"
           "        showMessage('Error: ' + (data.message || 'Unknown error'), 'danger');"
           "      }"
           "    })"
           "    .catch(function(err) {"
           "      showMessage('Error: ' + err.message, 'danger');"
           "    });"
           "}"
           "</script>"
           "</body>"
           "</html>";
}

const char *webui_get_mpu6050_status_html(void)
{
    return "";  // Removed - use API instead
}

const char *webui_get_nau7802_html(void)
{
    return "<!DOCTYPE html>"
           "<html lang=\"en\">"
           "<head>"
           "<meta charset=\"UTF-8\">"
           "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
           "<title>NAU7802 Scale Configuration</title>"
           "<style>"
           "* { box-sizing: border-box; }"
           "body { padding: 0; margin: 0; background-color: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; }"
           ".navbar { background-color: #212529; padding: 15px 0; margin-bottom: 20px; }"
           ".navbar-nav { display: flex; flex-direction: row; list-style: none; margin: 0; padding: 0 20px; justify-content: flex-start; align-items: center; width: 100%; }"
           ".navbar-nav li { margin: 0 15px; }"
           ".navbar-nav a { color: #ffffff; text-decoration: none; font-weight: 500; padding: 8px 16px; border-radius: 4px; transition: background-color 0.2s; }"
           ".navbar-nav a:hover { background-color: rgba(255, 255, 255, 0.1); }"
           ".navbar-nav a.active { background-color: #007bff; }"
           ".content-wrapper { padding: 20px; }"
           ".container { max-width: 800px; background: white; padding: 0; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin: 0 auto; overflow: hidden; }"
           ".page-header { background-color: #f8f9fa; padding: 20px 30px; border-bottom: 1px solid #dee2e6; }"
           ".page-header h1 { margin: 0; color: #212529; font-size: 1.75rem; font-weight: 700; text-transform: uppercase; }"
           ".page-content { padding: 30px; }"
           ".form-group { margin-bottom: 20px; }"
           "label { font-weight: 600; color: #555; display: block; margin-bottom: 5px; }"
           ".form-control { display: block; width: 100%; padding: 8px 12px; font-size: 14px; line-height: 1.5; color: #495057; background-color: #fff; border: 1px solid #ced4da; border-radius: 4px; }"
           ".form-control:focus { border-color: #80bdff; outline: 0; box-shadow: 0 0 0 0.2rem rgba(0,123,255,0.25); }"
           ".btn { display: inline-block; padding: 8px 16px; font-size: 14px; font-weight: 400; text-align: center; cursor: pointer; border: 1px solid transparent; border-radius: 4px; text-decoration: none; }"
           ".btn-primary { color: #fff; background-color: #007bff; border-color: #007bff; }"
           ".btn-primary:hover { background-color: #0069d9; border-color: #0062cc; }"
           ".alert { position: relative; padding: 12px 20px; margin-bottom: 20px; border: 1px solid transparent; border-radius: 4px; }"
           ".alert-success { color: #155724; background-color: #d4edda; border-color: #c3e6cb; }"
           ".alert-danger { color: #721c24; background-color: #f8d7da; border-color: #f5c6cb; }"
           ".alert-warning { color: #856404; background-color: #fff3cd; border-color: #ffeaa7; }"
           ".alert-info { color: #0c5460; background-color: #d1ecf1; border-color: #bee5eb; }"
           ".status-card { margin-bottom: 20px; border: 1px solid #dee2e6; border-radius: 4px; overflow: hidden; }"
           ".card-header { background-color: #f8f9fa; padding: 12px 20px; border-bottom: 1px solid #dee2e6; }"
           ".card-header h2 { margin: 0; font-size: 1.25rem; font-weight: 600; color: #212529; }"
           ".card-body { padding: 20px; }"
           "input[type=\"checkbox\"] { margin-right: 8px; }"
           "small { display: block; margin-top: 5px; color: #666; font-size: 12px; }"
           "</style>"
           "</head>"
           "<body>"
           "<nav class=\"navbar\">"
           "<ul class=\"navbar-nav\">"
           "<li><a href=\"/\">Device Configuration</a></li>"
           "<li><a href=\"/nau7802\" class=\"active\">NAU7802 Scale</a></li>"
           "<li><a href=\"/ota\">Firmware Update</a></li>"
           "</ul>"
           "</nav>"
           "<div class=\"content-wrapper\">"
           "<div class=\"container\">"
           "<div class=\"page-header\">"
           "<h1>NAU7802 Scale Configuration</h1>"
           "</div>"
           "<div class=\"page-content\">"
           "<div id=\"nau7802_message\" class=\"alert\" style=\"display: none;\"></div>"
           "<form id=\"nau7802ConfigForm\">"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Basic Configuration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"form-group\">"
           "<label>"
           "<input type=\"checkbox\" id=\"nau7802_enabled\" onchange=\"updateNau7802Status()\">"
           "<span>Enable NAU7802 Scale</span>"
           "</label>"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"nau7802_byte_offset\">Byte Offset:</label>"
           "<select id=\"nau7802_byte_offset\" class=\"form-control\" onchange=\"validateByteOffset()\">"
           "<option value=\"0\">0</option>"
           "<option value=\"1\">1</option>"
           "<option value=\"2\">2</option>"
           "<option value=\"3\">3</option>"
           "<option value=\"4\">4</option>"
           "<option value=\"5\">5</option>"
           "<option value=\"6\">6</option>"
           "<option value=\"7\">7</option>"
           "<option value=\"8\">8</option>"
           "<option value=\"9\">9</option>"
           "<option value=\"10\">10</option>"
           "<option value=\"11\">11</option>"
           "<option value=\"12\">12</option>"
           "<option value=\"13\">13</option>"
           "<option value=\"14\">14</option>"
           "<option value=\"15\">15</option>"
           "<option value=\"16\">16</option>"
           "<option value=\"17\">17</option>"
           "<option value=\"18\">18</option>"
           "<option value=\"19\">19</option>"
           "<option value=\"20\">20</option>"
           "<option value=\"21\">21</option>"
           "<option value=\"22\">22</option>"
           "</select>"
           "<small>Starting byte position in Assembly 100 (10 bytes total: 4 bytes weight + 4 bytes raw + 1 byte unit + 1 byte status). Maximum offset: 22 (32 - 10)</small>"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"nau7802_unit\">Weight Unit:</label>"
           "<select id=\"nau7802_unit\" class=\"form-control\" onchange=\"updateCalibrationUnitHint()\">"
           "<option value=\"0\">Grams (g)</option>"
           "<option value=\"1\">Pounds (lbs)</option>"
           "<option value=\"2\">Kilograms (kg)</option>"
           "</select>"
           "<small>Weight is stored in assembly as integer scaled by 100 (e.g., 100.24 lbs = 10024)</small>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Device Settings</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"form-group\">"
           "<label for=\"nau7802_gain\">Gain:</label>"
           "<select id=\"nau7802_gain\" class=\"form-control\">"
           "<option value=\"0\">x1</option>"
           "<option value=\"1\">x2</option>"
           "<option value=\"2\">x4</option>"
           "<option value=\"3\">x8</option>"
           "<option value=\"4\">x16</option>"
           "<option value=\"5\">x32</option>"
           "<option value=\"6\">x64</option>"
           "<option value=\"7\">x128</option>"
           "</select>"
           "<small>Programmable Gain Amplifier (PGA) gain. Higher gain = higher sensitivity. <strong>Note:</strong> Changing gain automatically triggers AFE (Analog Front End) calibration, which calibrates the chip's internal hardware. This is different from weight calibration below.</small>"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"nau7802_sample_rate\">Sample Rate:</label>"
           "<select id=\"nau7802_sample_rate\" class=\"form-control\">"
           "<option value=\"0\">10 SPS</option>"
           "<option value=\"1\">20 SPS</option>"
           "<option value=\"2\">40 SPS</option>"
           "<option value=\"3\">80 SPS</option>"
           "<option value=\"7\">320 SPS</option>"
           "</select>"
           "<small>Samples per second. Lower rates = more stable, higher rates = faster updates. <strong>Note:</strong> Changing sample rate automatically triggers AFE (Analog Front End) calibration, which calibrates the chip's internal hardware. This is different from weight calibration below.</small>"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"nau7802_channel\">Channel:</label>"
           "<select id=\"nau7802_channel\" class=\"form-control\">"
           "<option value=\"0\">Channel 1</option>"
           "<option value=\"1\">Channel 2</option>"
           "</select>"
           "<small>Select active channel (NAU7802 supports dual-channel operation)</small>"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"nau7802_ldo\">LDO Voltage:</label>"
           "<select id=\"nau7802_ldo\" class=\"form-control\">"
           "<option value=\"0\">4.5V</option>"
           "<option value=\"1\">4.2V</option>"
           "<option value=\"2\">3.9V</option>"
           "<option value=\"3\">3.6V</option>"
           "<option value=\"4\">3.3V</option>"
           "<option value=\"5\">3.0V</option>"
           "<option value=\"6\">2.7V</option>"
           "<option value=\"7\">2.4V</option>"
           "</select>"
           "<small>Low-Dropout Regulator voltage. 3.3V recommended for Qwiic. Changes require reboot.</small>"
           "</div>"
           "<div class=\"form-group\">"
           "<label for=\"nau7802_average\">Reading Average (Samples):</label>"
           "<input type=\"number\" id=\"nau7802_average\" class=\"form-control\" value=\"1\" min=\"1\" max=\"50\" style=\"width: 100px;\">"
           "<small>Number of samples to average for regular weight readings (1-50). Higher values = more stable but slower updates. Default: 1 (no averaging). <strong>Note:</strong> This is separate from calibration averaging below.</small>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Status & Readings</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"form-group\">"
           "<label>Device Status:</label>"
           "<div id=\"nau7802_status\" style=\"padding: 10px; background-color: #f8f9fa; border-radius: 4px; font-family: monospace; font-size: 12px;\">Loading...</div>"
           "</div>"
           "</div>"
           "</div>"
           "<div class=\"status-card\">"
           "<div class=\"card-header\">"
           "<h2>Calibration</h2>"
           "</div>"
           "<div class=\"card-body\">"
           "<div class=\"form-group\">"
           "<label>Weight Calibration (Software):</label>"
           "<p style=\"font-size: 12px; color: #666; margin-bottom: 10px;\">These calibrations convert raw ADC readings to weight values. Use after changing load cells or when readings are inaccurate.</p>"
           "<div style=\"display: flex; gap: 10px; flex-wrap: wrap;\">"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"nau7802Tare()\" id=\"nau7802_tare_btn\">Tare (Zero)</button>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"nau7802KnownWeight()\" id=\"nau7802_cal_btn\">Calibrate with Known Weight</button>"
           "</div>"
           "<div style=\"margin-top: 15px; padding-top: 15px; border-top: 1px solid #dee2e6;\">"
           "<label>AFE Calibration (Hardware):</label>"
           "<p style=\"font-size: 12px; color: #666; margin-bottom: 10px;\">Calibrates the chip's Analog Front End hardware. Automatically performed when gain or sample rate changes. Use this button to manually recalibrate if needed.</p>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"nau7802AfeCalibrate()\" id=\"nau7802_afe_btn\">Calibrate AFE</button>"
           "</div>"
           "<div id=\"nau7802_cal_input\" style=\"display: none; margin-top: 10px;\">"
           "<input type=\"number\" id=\"nau7802_known_weight\" class=\"form-control\" placeholder=\"Known weight\" step=\"0.1\" min=\"0\" style=\"margin-bottom: 10px;\">"
           "<small id=\"nau7802_cal_unit_hint\" style=\"color: #666; display: block; margin-bottom: 10px;\">Enter weight in grams</small>"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"nau7802PerformCalibration()\">Perform Calibration</button>"
           "<button type=\"button\" class=\"btn\" onclick=\"cancelCalibration()\" style=\"background-color: #6c757d; color: white; margin-left: 10px;\">Cancel</button>"
           "</div>"
           "</div>"
           "</div>"
           "</div>"
           "<div style=\"text-align: center; margin-top: 20px;\">"
           "<button type=\"button\" class=\"btn btn-primary\" onclick=\"saveNau7802Config()\">Save Configuration</button>"
           "</div>"
           "</form>"
           "</div>"
           "<footer style=\"text-align: center; padding: 20px 30px; border-top: 1px solid #dee2e6; color: #666; background-color: #f8f9fa;\">OpENer Ethernet/IP for ESP32-P4 | Adam G Sweeney 11-15-2025</footer>"
           "</div>"
           "</div>"
           "<script>"
           "function showMessage(text, type) {"
           "  const msg = document.getElementById('nau7802_message');"
           "  if (msg) {"
           "    msg.textContent = text;"
           "    msg.className = 'alert alert-' + type;"
           "    msg.style.display = 'block';"
           "    setTimeout(function() { msg.style.display = 'none'; }, 5000);"
           "  } else {"
           "    console.log('[' + type.toUpperCase() + '] ' + text);"
           "  }"
           "}"
           "function loadNau7802Config() {"
           "  fetch('/api/nau7802')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const enabledCheckbox = document.getElementById('nau7802_enabled');"
           "      const byteOffsetSelect = document.getElementById('nau7802_byte_offset');"
           "      const unitSelect = document.getElementById('nau7802_unit');"
           "      const gainSelect = document.getElementById('nau7802_gain');"
           "      const sampleRateSelect = document.getElementById('nau7802_sample_rate');"
           "      const channelSelect = document.getElementById('nau7802_channel');"
           "      const ldoSelect = document.getElementById('nau7802_ldo');"
           "      const averageInput = document.getElementById('nau7802_average');"
           "      if (enabledCheckbox && data.enabled !== undefined) {"
           "        enabledCheckbox.checked = data.enabled;"
           "      }"
           "      if (byteOffsetSelect && data.byte_offset !== undefined) {"
           "        byteOffsetSelect.value = data.byte_offset;"
           "      }"
           "      if (unitSelect) {"
           "        if (data.unit_code !== undefined) {"
           "          unitSelect.value = data.unit_code;"
           "        } else if (data.unit !== undefined && typeof data.unit === 'number') {"
           "          unitSelect.value = data.unit;"
           "        }"
           "      }"
           "      if (gainSelect && data.gain !== undefined) {"
           "        gainSelect.value = data.gain;"
           "      }"
           "      if (sampleRateSelect && data.sample_rate !== undefined) {"
           "        sampleRateSelect.value = data.sample_rate;"
           "      }"
           "      if (channelSelect && data.channel !== undefined) {"
           "        channelSelect.value = data.channel;"
           "      }"
           "      if (ldoSelect && data.ldo_value !== undefined) {"
           "        ldoSelect.value = data.ldo_value;"
           "      }"
           "      if (averageInput && data.average !== undefined) {"
           "        averageInput.value = data.average;"
           "      }"
           "      updateCalibrationUnitHint();"
           "      updateNau7802Status();"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to load NAU7802 configuration:', err);"
           "      const statusDiv = document.getElementById('nau7802_status');"
           "      if (statusDiv) statusDiv.textContent = 'Error loading configuration';"
           "    });"
           "}"
           "function updateNau7802Status() {"
           "  fetch('/api/nau7802')"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      const statusDiv = document.getElementById('nau7802_status');"
           "      if (!statusDiv) return;"
           "      let status = [];"
           "      status.push('Initialized: ' + (data.initialized ? 'Yes' : 'No'));"
           "      if (data.initialized) {"
           "        status.push('Connected: ' + (data.connected ? 'Yes' : 'No'));"
           "        status.push('Available: ' + (data.available ? 'Yes' : 'No'));"
           "        if (data.weight !== undefined) {"
           "          const unitStr = data.unit || 'g';"
           "          status.push('Weight: ' + data.weight.toFixed(3) + ' ' + unitStr);"
           "        }"
           "        if (data.raw_reading !== undefined) {"
           "          status.push('Raw ADC: ' + data.raw_reading);"
           "        }"
           "        if (data.calibration_factor !== undefined) {"
           "          status.push('Cal Factor: ' + data.calibration_factor.toFixed(6));"
           "        }"
           "        if (data.zero_offset !== undefined) {"
           "          status.push('Zero Offset: ' + data.zero_offset.toFixed(3));"
           "        }"
           "        if (data.gain_label) {"
           "          status.push('Gain: ' + data.gain_label);"
           "        }"
           "        if (data.sample_rate_label) {"
           "          status.push('Sample Rate: ' + data.sample_rate_label + ' SPS');"
           "        }"
           "        if (data.channel_label) {"
           "          status.push('Channel: ' + data.channel_label);"
           "        }"
           "        if (data.ldo_voltage !== undefined) {"
           "          status.push('LDO: ' + data.ldo_voltage.toFixed(1) + 'V');"
           "        }"
           "        if (data.revision_code !== undefined) {"
           "          status.push('Revision: 0x' + data.revision_code.toString(16).toUpperCase());"
           "        }"
           "        if (data.status) {"
           "          if (data.status.power_digital !== undefined) {"
           "            status.push('Power Digital: ' + (data.status.power_digital ? 'On' : 'Off'));"
           "          }"
           "          if (data.status.power_analog !== undefined) {"
           "            status.push('Power Analog: ' + (data.status.power_analog ? 'On' : 'Off'));"
           "          }"
           "          if (data.status.calibration_error) {"
           "            status.push('CAL ERROR!');"
           "          }"
           "        }"
           "      }"
           "      statusDiv.textContent = status.join(' | ');"
           "      const tareBtn = document.getElementById('nau7802_tare_btn');"
           "      const calBtn = document.getElementById('nau7802_cal_btn');"
           "      if (tareBtn) tareBtn.disabled = !data.initialized || !data.connected;"
           "      if (calBtn) calBtn.disabled = !data.initialized || !data.connected;"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to update NAU7802 status:', err);"
           "      const statusDiv = document.getElementById('nau7802_status');"
           "      if (statusDiv) statusDiv.textContent = 'Error loading status';"
           "    });"
           "}"
           "function saveNau7802Config() {"
           "  const enabledCheckbox = document.getElementById('nau7802_enabled');"
           "  const byteOffsetSelect = document.getElementById('nau7802_byte_offset');"
           "  const unitSelect = document.getElementById('nau7802_unit');"
           "  const gainSelect = document.getElementById('nau7802_gain');"
           "  const sampleRateSelect = document.getElementById('nau7802_sample_rate');"
           "  const channelSelect = document.getElementById('nau7802_channel');"
           "  const ldoSelect = document.getElementById('nau7802_ldo');"
           "  const averageInput = document.getElementById('nau7802_average');"
           "  const assemblySize = 32;"
           "  const nau7802DataSize = 10;"
           "  const maxOffset = assemblySize - nau7802DataSize;"
           "  const data = {"
           "    enabled: enabledCheckbox ? enabledCheckbox.checked : false,"
           "    byte_offset: byteOffsetSelect ? parseInt(byteOffsetSelect.value) || 0 : 0,"
           "    unit: unitSelect ? parseInt(unitSelect.value) || 1 : 1,"
           "    gain: gainSelect ? parseInt(gainSelect.value) || 7 : 7,"
           "    sample_rate: sampleRateSelect ? parseInt(sampleRateSelect.value) || 3 : 3,"
           "    channel: channelSelect ? parseInt(channelSelect.value) || 0 : 0,"
           "    ldo_value: ldoSelect ? parseInt(ldoSelect.value) || 4 : 4,"
           "    average: averageInput ? parseInt(averageInput.value) || 1 : 1"
           "  };"
           "  if (data.byte_offset < 0 || data.byte_offset > maxOffset) {"
           "    showMessage('Byte offset must be between 0 and ' + maxOffset + ' (assembly size ' + assemblySize + ' - data size ' + nau7802DataSize + ')', 'danger');"
           "    return;"
           "  }"
           "  fetch('/api/nau7802', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify(data)"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message || 'Configuration saved successfully', 'success');"
           "        updateNau7802Status();"
           "      } else {"
           "        showMessage('Failed to save configuration', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to save NAU7802 configuration:', err);"
           "      showMessage('Failed to save configuration', 'danger');"
           "    });"
           "}"
           "function nau7802Tare() {"
           "  if (!confirm('This will set the current reading as zero. Continue?')) return;"
           "  fetch('/api/nau7802/calibrate', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify({ action: 'tare' })"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message || 'Tare completed successfully', 'success');"
           "        setTimeout(updateNau7802Status, 1000);"
           "      } else {"
           "        showMessage(data.message || 'Tare failed', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to perform tare:', err);"
           "      showMessage('Failed to perform tare', 'danger');"
           "    });"
           "}"
           "function validateByteOffset() {"
           "  const byteOffsetSelect = document.getElementById('nau7802_byte_offset');"
           "  if (!byteOffsetSelect) return;"
           "  const assemblySize = 32;"
           "  const nau7802DataSize = 10;"
           "  const maxOffset = assemblySize - nau7802DataSize;"
           "  const selectedOffset = parseInt(byteOffsetSelect.value) || 0;"
           "  if (selectedOffset > maxOffset) {"
           "    showMessage('Byte offset ' + selectedOffset + ' is too large. Maximum is ' + maxOffset + ' (assembly size ' + assemblySize + ' - data size ' + nau7802DataSize + ')', 'danger');"
           "    byteOffsetSelect.value = maxOffset;"
           "  }"
           "}"
           "function updateCalibrationUnitHint() {"
           "  const unitSelect = document.getElementById('nau7802_unit');"
           "  const hint = document.getElementById('nau7802_cal_unit_hint');"
           "  if (unitSelect && hint) {"
           "    const unit = parseInt(unitSelect.value);"
           "    const unitStr = (unit === 0) ? 'grams' : (unit === 1) ? 'lbs' : 'kg';"
           "    hint.textContent = 'Enter weight in ' + unitStr;"
           "  }"
           "}"
           "function nau7802KnownWeight() {"
           "  document.getElementById('nau7802_cal_input').style.display = 'block';"
           "  updateCalibrationUnitHint();"
           "  document.getElementById('nau7802_known_weight').focus();"
           "}"
           "function cancelCalibration() {"
           "  document.getElementById('nau7802_cal_input').style.display = 'none';"
           "}"
           "function nau7802AfeCalibrate() {"
           "  if (!confirm('This will calibrate the Analog Front End (AFE) hardware. The scale must be empty and stable. Continue?')) return;"
           "  const btn = document.getElementById('nau7802_afe_btn');"
           "  if (btn) btn.disabled = true;"
           "  fetch('/api/nau7802/calibrate', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify({ action: 'afe' })"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message || 'AFE calibration completed successfully', 'success');"
           "        setTimeout(updateNau7802Status, 1000);"
           "      } else {"
           "        showMessage(data.message || 'AFE calibration failed', 'danger');"
           "      }"
           "      if (btn) btn.disabled = false;"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to perform AFE calibration:', err);"
           "      showMessage('Failed to perform AFE calibration', 'danger');"
           "      if (btn) btn.disabled = false;"
           "    });"
           "}"
           "function nau7802PerformCalibration() {"
           "  const weightInput = document.getElementById('nau7802_known_weight');"
           "  const unitSelect = document.getElementById('nau7802_unit');"
           "  const knownWeight = parseFloat(weightInput.value);"
           "  if (isNaN(knownWeight) || knownWeight <= 0) {"
           "    showMessage('Please enter a valid weight greater than 0', 'danger');"
           "    return;"
           "  }"
           "  const unit = unitSelect ? parseInt(unitSelect.value) : 1;"
           "  const unitStr = (unit === 0) ? 'g' : (unit === 1) ? 'lbs' : 'kg';"
           "  if (!confirm('Place ' + knownWeight + ' ' + unitStr + ' on the scale and click OK to calibrate.')) return;"
           "  fetch('/api/nau7802/calibrate', {"
           "    method: 'POST',"
           "    headers: { 'Content-Type': 'application/json' },"
           "    body: JSON.stringify({ action: 'calibrate', known_weight: knownWeight })"
           "  })"
           "    .then(r => {"
           "      if (!r.ok) throw new Error('HTTP ' + r.status);"
           "      return r.json();"
           "    })"
           "    .then(data => {"
           "      if (data.status === 'ok') {"
           "        showMessage(data.message || 'Calibration completed successfully', 'success');"
           "        document.getElementById('nau7802_cal_input').style.display = 'none';"
           "        weightInput.value = '';"
           "        setTimeout(updateNau7802Status, 1000);"
           "      } else {"
           "        showMessage(data.message || 'Calibration failed', 'danger');"
           "      }"
           "    })"
           "    .catch(err => {"
           "      console.error('Failed to perform calibration:', err);"
           "      showMessage('Failed to perform calibration', 'danger');"
           "    });"
           "}"
           "window.onload = function() {"
           "  loadNau7802Config();"
           "  setInterval(updateNau7802Status, 2000);"
           "};"
           "</script>"
           "</body>"
           "</html>";
}
